name: Build e Deploy React

on:
  push:
    branches:
      - 'main'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build and deploy
        working-directory: ./website
        run: npm ci
      - name: build
        working-directory: ./website
        run: npm run build
      - name: Authorizing Github action
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
        uses: oleksiyrudenko/gha-git-credentials@v1
      - name: git
        working-directory: ./website
        run: |
          git --work-tree build add --all
          git --work-tree build commit -m 'deploy files'
          git push origin HEAD:gh-pages --force

