name: Build e Deploy React

on:
  push:
    branches:
      - 'main'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: build and deploy
        working-directory: ./website
        run: |
          npm ci
          npm run build
          git --work-tree build add --all
          git --work-tree build commit -m 'deploy files'
          git push origin HEAD:gh-pages --force

