name: Build e Deploy React

on:
  push:
    branches:
      - 'main'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
      
      steps:
       - run: npm ci
         shell: bash
       - run: npm run build
         shell: bash
       - run: git --work-tree build add --all
         shell: bash
       - run: git --work-tree build commit -m 'deploy files'
         shell: bash
       - run: git push origin HEAD:gh-pages --force
         shell: bash
